[default.variables]

pkgs = [
# replacement of builtin
    "bat",                  # replace cat
    "bottom",               # replace top
    "ctags",                # for tagbar nvim plug
    "dua-cli",              # replace du
    "fd",                   # replace find
    "lsd",                  # replace ls
    "mcfly",                # shell-history
    "ripgrep",              # replace grep
    "trash-cli",            # replace rm with a trash
    "zoxide",               # replace cd

# other rust application
    "eva",                  # make calculator

# application
    "discord",
    "evince",

# dev tool
    "git",
    "git-delta",           # new diff
    "glow",                # markdow view
    "neovim",              # editor
    "python-shtab",        # generate shell completion
    "tmux",                # terminal multiplexer
    "wget",                # get webpage
    "zsh",                 # shell
    "zsh-completions",     # completion for zsh

# extraction
    "tar",
    "unrar",
    "unzip",

# compilers / builder
    "gcc",
    "lua",
    "npm",
    "ocaml",
    "opam",
    "perl",
    "ruby",
    "rustup",
    #"python3",

# system
    "pavucontrol",
    "pcmanfm",
    "topgrade",

# font
    "ttf-fira-code",

# lsp server
    "bash-language-server", # bash lsp
    "ctags",                # tags in vim
    "lua-language-server",  # lua lsp
    "taplo"                 # toml
]

# cargo pkgs
cargo_pkgs = [
]

#python pkgs
pip_pkgs = [
]

# npm pkgs
npm_pkgs = [
# lsp server
    "bash-language-server", # bash lsp
    "lua-language-server",  # lua lsp
    "taplo"                 # toml
]

pm_install = "pamac install"
pm_update = "pamac update"
