[default.variables]

sys_pkgs = [
    # application
    "discord",
    "kitty",   # terminal
    "evince",  # pdf viewer

    # dev tool
    "git",
    "glow",            # markdow view
    "neovim",          # editor
    "python-shtab",    # generate shell completion
    "tmux",            # terminal multiplexer
    "wget",            # get webpage
    "zsh",             # shell
    "zsh-completions", # completion for zsh

    # extraction
    "tar",
    "unrar",
    "unzip",

    # compilers / builder
    "gcc",
    "lua",
    "npm",
    "ocaml",
    "opam",
    "perl",
    "ruby",
    "rustup",
    "python-pip",

    # system
    "pavucontrol",
    "pcmanfm",

    # font
    "ttf-fira-code",

    # lsp server
    "bash-language-server", # bash lsp
    "ctags",                # tags in vim
    "lua-language-server",  # lua lsp
    "taplo",                # toml
]

sys_install = "pamac install"
sys_update = "pamac update"
