[default.variables]

pkgs = [
    "bash-language-server",
    "bat",
    "bottom",
    "direnv",
    "discord",
    "dua-cli",
    "eva",
    "evince",
    "fd",
    "gcc",
    "git",
    "git-delta",
    "lua",
    "lua-language-server",
    "mcfly",
    "neovim",
    "npm",
    "ocaml",
    "opam",
    "pavucontrol",
    "pcmanfm",
    "perl",
    "python-shtab",
    "ripgrep",
    "ruby",
    "rustup",
    "tar",
    "tmux",
    "topgrade",
    "trash-cli",
    "ttf-fira-code",
    "unrar",
    "unzip",
    "wget",
    "zoxide",
    "zsh-completions",
    #"python3",
]
pm_install = "pamac install"

