
[default.variables]

pkgs = [

# application
    # "discord",
    "evince",

# dev tool
    "git",
    #"glow",                # markdow view -- install manually (view on github)
    "neovim",              # editor
    "tmux",                # terminal multiplexer
    "wget",                # get webpage
    "zsh",                 # shell

# extraction
    "tar",
    "unrar",
    "unzip",

# compilers / builder
    "gcc",
    "lua5.4",
    "npm",
    "ocaml",
    "opam",
    "perl",
    "ruby",
    #"rustup",
    #"python3",

# system
    "pavucontrol",
    "pcmanfm",

# font
    "fonts-firacode",

# lsp server
    "universal-ctags",                # tags in vim
]

# cargo pkgs
cargo_pkgs = [

# replacement of builtin
    "bat",                  # replace cat
    "bottom",               # replace top
    "dua-cli",              # replace du
    "fd",                   # replace find
    "lsd",                  # replace ls
    "mcfly",                # shell-history
    "ripgrep",              # replace grep
    "trash-cli",            # replace rm with a trash
    "zoxide",               # replace cd

# other rust application
    "eva",                  # make calculator

# dev tool
    "git-delta",            # new diff

# system
    "topgrade",
]

#python package
pip_pkgs = [
    "shab"                  # generate shell completion

]

# npm package
npm_pkgs = [
# lsp server
    "bash-language-server", # bash lsp
    "lua-language-server",  # lua lsp
    "taplo"                 # toml
]

pm_install = "sudo apt-get install"
pm_update = "sudo apt-get update"
