[helpers]

[default.variables]

[shell.variables]
editor = "nvim"

[neovim.files]
nvim = "~/.config/nvim"

[git.files]
gitconfig = "~/.gitconfig"

[git.variables]
email = "jeremy.damour2@gmail.com"
name = "jeremy.damour"
