[helpers]

[default.variables]
email = "jeremy.damour2@gmail.com"
install_pkgs = true
cargo_pkgs = [
    "lsd",
]
arch_pkgs = [
    "bash-language-server",
    "bat",
    "bottom",
    "dua-cli",
    "eva",
    "evince",
    "fd",
    "git",
    "git-delta",
    "lua",
    "mcfly",
    "neovim",
    "ripgrep",
    "trash-cli",
    "wget",
    "zsh-completions"
]

[shell.variables]
editor = "nvim"
#git
[git]
depends = ["shell", "default"]

[git.files]
gitconfig = "~/.gitconfig"

[git.variables]
name = "jeremy.damour"

#neovim
[neovim.files]
nvim = "~/.config/nvim"

#sway
#[sway.files]
#"sway/config.d" = "~/.config/sway/config.d"
#"sway/definition.d" = "~/.config/sway/definitions.d"

#zsh
[zsh]
depends = ["shell"]

[zsh.variables]
config_dir = "~/.config/zsh"

[zsh.files]
"zsh/zshrc" = "~/.config/zsh/.zshrc"
"zsh/config" = "~/.config/zsh"

[zsh.files."zsh/plugins/powerlevel10k"]
target="~/.oh-my-zsh/themes/powerlevel10k"
type="symbolic"

[zsh.files."zsh/plugins/zsh-autosuggestions"]
target="~/.oh-my-zsh/plugins/zsh-autosuggestions"
type="symbolic"

[zsh.files."zsh/plugins/zsh-syntax-highlighting"]
target="~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
type="symbolic"
