includes = [
    ".dotter/arch.toml"
]

packages = [
    "discord",
    "git",
    "kitty",
    "neovim",
    "sway",
    "tmux",
    "vscode",
    "waybar",
    "zsh",
    "waybar",
    #"foot",
]

#[files]

[variables]
install_pkgs = false
update_pkgs = false
